Fixing an issue with the promise shim
dojo/shim pull request #53
Opened 2016-11-17 19:47 UTC by rorticus

**Type:** bug

**Description:** 

A fix for a problem with `Promise.all`. The arguments accept a `Thenable`, but the actual code was checking specifically for a `Promise` type later on. This meant that you couldn't actually pass in a `Thenable` that wasn't a `Promise`.

Please review this checklist before submitting your PR:

* [ ] There is a related issue
* [x] All contributors have signed a CLA
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] The code passes the CI tests
* [ ] Unit or Functional tests are included in the PR
* [x] The PR increases or maintains the overall unit test coverage percentage
* [x] The code is ready to be merged

2016-11-25 14:01 UTC, kitsonk requested changes
We should add a test for this... that something tenable, that isn't a promise passes.

2016-11-28 14:25 UTC, rorticus commented
> We should add a test for this

Added. It looks like `Promise.race` is already covered by a similar test.

2016-11-29 11:29 UTC, agubler commented
looking for @kitsonk's re-review on this one

2016-11-29 17:12 UTC, agubler approved these changes

2016-11-29 17:12 UTC, merged