Adding ES8 padStart/padEnd to string utils, issue #27
dojo/shim pull request #54
Opened 2016-11-17 20:33 UTC by rorticus

**Type:** feature

**Description:** 

Adding ES 8 `padStart` and `padEnd` to string shim.

**Related Issue:** #27 

Please review this checklist before submitting your PR:

* [x] There is a related issue
* [x] All contributors have signed a CLA
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] The code passes the CI tests
* [x] Unit or Functional tests are included in the PR
* [x] The PR increases or maintains the overall unit test coverage percentage
* [x] The code is ready to be merged

2016-11-25 14:03 UTC, kitsonk requested changes
Firefox 50 has this natively, not under flags... We should update the version of our FF on SauceLabs and see if this passes the test.

2016-11-28 13:39 UTC, rorticus commented
> Firefox 50 has this natively, not under flags... We should update the version of our FF on SauceLabs and see if this passes the test.

OK, I ran it under Firefox 51 and tested it against native. There were some failures because I was throwing errors on invalid pad length values (`null`, `undefined`, `-1`) and apparently Firefox just sets the pad length to 0 in those cases.  I've updated the shim code to act similarly and the tests to reflect it, all tests now pass through saucelabs.

I wasn't sure if I should updated `intern-saucelabs.ts` to include the new Firefox version because we can't just specify "50" as the latest specific version I can target is 49 and I have to pass the version as "beta" if I want to use 51. Let me know if you want me to use the beta version of Firefox and I'll updated the intern config accordingly!

2016-11-29 18:24 UTC, kitsonk commented
> Let me know if you want me to use the beta version of Firefox and I'll updated the intern config accordingly!

Let's use the beta version for now, but we should open up an issue to lock it down at some point in the future when there is a properly released version that SauceLabs supports.

2016-11-29 18:24 UTC, kitsonk approved these changes
👍 (once we update the CI as agreed)

2016-11-29 20:37 UTC, rorticus commented
OK it looks like if I downgrade to Windows 10, we can use Firefox 50 without using any beta channels. Woot!

2016-11-29 20:38 UTC, merged