Implementing Observables shim, issue #59
dojo/shim pull request #62
Opened 2016-12-05 14:39 UTC by rorticus

**Type:** feature

**Description:** 

Shim implementation of [ES observables spec](https://github.com/tc39/proposal-observable). Non-spec functionality (i.e., `toPromise`, `map`, `filter`) will go in core.

**Related Issue:** #59 

Please review this checklist before submitting your PR:

* [x] There is a related issue
* [x] All contributors have signed a CLA
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] The code passes the CI tests
* [x] Unit or Functional tests are included in the PR
* [x] The PR increases or maintains the overall unit test coverage percentage
* [x] The code is ready to be merged

2016-12-05 14:46 UTC, rorticus commented
Also, I should note.. I talked with @matt-gadd about the fact that [our interface](https://github.com/dojo/interfaces/blob/master/src/observables.d.ts) calls a property `isUnsubscribed` and the spec calls it `closed`. We decided to go with the spec, knowing that there are going to be some breaking changes.

2016-12-05 20:17 UTC, rorticus commented
OK don't review this just yet.. I ran against the tests that Ant mentioned and I've got some things to fix up first :)

2016-12-06 19:37 UTC, rorticus commented
OK. Refactored quite a bit... All the ES spec tests pass now!

```
[90mStarting tests...[39m

[1mObservable constructor[22m

[1m  Argument types[22m
    The first argument cannot be a non-callable object [1m[32mOK[39m[22m
    The first argument cannot be a primative value [1m[32mOK[39m[22m
    The first argument cannot be a primative value [1m[32mOK[39m[22m
    The first argument cannot be a primative value [1m[32mOK[39m[22m
    The first argument cannot be a primative value [1m[32mOK[39m[22m
    The first argument can be a function [1m[32mOK[39m[22m

[1m  Observable.prototype has a constructor property[22m
    Property constructor exists on the object [1m[32mOK[39m[22m
    Property has a function value [1m[32mOK[39m[22m
    Function length is 1 [1m[32mOK[39m[22m
    Property is writable [1m[32mOK[39m[22m
    Property is non-enumerable [1m[32mOK[39m[22m
    Property is configurable [1m[32mOK[39m[22m
    Observable.prototype.constructor === Observable [1m[32mOK[39m[22m

[1m  Subscriber function is not called by constructor[22m
    The constructor does not call the subscriber function [1m[32mOK[39m[22m

[1mObservable.prototype.subscribe[22m

[1m  Observable.prototype has a subscribe property[22m
    Property subscribe exists on the object [1m[32mOK[39m[22m
    Property has a function value [1m[32mOK[39m[22m
    Function length is 1 [1m[32mOK[39m[22m
    Property is writable [1m[32mOK[39m[22m
    Property is non-enumerable [1m[32mOK[39m[22m
    Property is configurable [1m[32mOK[39m[22m

[1m  Argument type[22m
    Throws if observer is not an object [1m[32mOK[39m[22m
    Throws if observer is not an object [1m[32mOK[39m[22m
    Throws if observer is not an object [1m[32mOK[39m[22m
    Throws if observer is not an object [1m[32mOK[39m[22m
    Throws if observer is not an object [1m[32mOK[39m[22m
    Any object may be an observer [1m[32mOK[39m[22m
    Any object may be an observer [1m[32mOK[39m[22m
    Any object may be an observer [1m[32mOK[39m[22m

[1m  Function arguments[22m
    First argument is next callback [1m[32mOK[39m[22m
    Second argument is error callback [1m[32mOK[39m[22m
    Third argument is complete callback [1m[32mOK[39m[22m
    Second and third arguments are optional [1m[32mOK[39m[22m
    Second and third arguments are optional [1m[32mOK[39m[22m

[1m  Subscriber arguments[22m
    Subscriber is called with an observer [1m[32mOK[39m[22m
    Subscriber is called with an observer [1m[32mOK[39m[22m
    Subscriber is called with an observer [1m[32mOK[39m[22m
    Subscriber is called with an observer [1m[32mOK[39m[22m
    Subscription observer's constructor property is Object [1m[32mOK[39m[22m

[1m  Subscriber return types[22m
    Undefined can be returned [1m[32mOK[39m[22m
    Null can be returned [1m[32mOK[39m[22m
    Functions can be returned [1m[32mOK[39m[22m
    Subscriptions can be returned [1m[32mOK[39m[22m
    Non callable, non-subscription objects cannot be returned [1m[32mOK[39m[22m
    Non-functions cannot be returned [1m[32mOK[39m[22m
    Non-functions cannot be returned [1m[32mOK[39m[22m

[1m  Returns a subscription object[22m
    Property unsubscribe exists on the object [1m[32mOK[39m[22m
    Property has a function value [1m[32mOK[39m[22m
    Function length is 0 [1m[32mOK[39m[22m
    Property is writable [1m[32mOK[39m[22m
    Property is non-enumerable [1m[32mOK[39m[22m
    Property is configurable [1m[32mOK[39m[22m
    Property closed exists on the object [1m[32mOK[39m[22m
    Property has a getter [1m[32mOK[39m[22m
    Function length is 0 [1m[32mOK[39m[22m
    Property does not have a setter [1m[32mOK[39m[22m
    Property is non-enumerable [1m[32mOK[39m[22m
    Property is configurable [1m[32mOK[39m[22m
    Subscribe returns an object [1m[32mOK[39m[22m
    Contructor property is Object [1m[32mOK[39m[22m
    closed property returns false before unsubscription [1m[32mOK[39m[22m
    Unsubscribe returns undefined [1m[32mOK[39m[22m
    Unsubscribe calls the cleanup function [1m[32mOK[39m[22m
    closed property is true after calling unsubscribe [1m[32mOK[39m[22m

[1m  Cleanup function[22m
    The cleanup function is called when unsubscribing [1m[32mOK[39m[22m
    The cleanup function is not called again when unsubscribe is called again [1m[32mOK[39m[22m
    The cleanup function is called when an error is sent to the sink [1m[32mOK[39m[22m
    The cleanup function is called when a complete is sent to the sink [1m[32mOK[39m[22m
    If a subscription is returned, then unsubscribe is called on cleanup [1m[32mOK[39m[22m
    Arguments are not forwarded to the unsubscribe function [1m[32mOK[39m[22m

[1m  Exceptions thrown from the subscriber[22m
    Subscribe throws if the observer does not handle errors [1m[32mOK[39m[22m
    Subscribe does not throw if the observer has an error method [1m[32mOK[39m[22m
    Subscribe sends an error to the observer [1m[32mOK[39m[22m

[1m  Start method[22m
    If the observer has a start method, it is called [1m[32mOK[39m[22m
    Start is called with the observer as the this value [1m[32mOK[39m[22m
    Start is called with the subscription as the first argument [1m[32mOK[39m[22m
    Start is called before the subscriber function is called [1m[32mOK[39m[22m
    If unsubscribe is called from start, the subscriber is not called [1m[32mOK[39m[22m

[1mObservable.prototype[Symbol.observable][22m

[1m  Observable.prototype has a Symbol.observable method[22m
    Property Symbol(observable) exists on the object [1m[32mOK[39m[22m
    Property has a function value [1m[32mOK[39m[22m
    Function length is 0 [1m[32mOK[39m[22m
    Property is writable [1m[32mOK[39m[22m
    Property is non-enumerable [1m[32mOK[39m[22m
    Property is configurable [1m[32mOK[39m[22m

[1m  Return value[22m
    Returns the 'this' value [1m[32mOK[39m[22m

[1mObservable.of[22m

[1m  Observable has an of property[22m
    Property of exists on the object [1m[32mOK[39m[22m
    Property has a function value [1m[32mOK[39m[22m
    Function length is 0 [1m[32mOK[39m[22m
    Property is writable [1m[32mOK[39m[22m
    Property is non-enumerable [1m[32mOK[39m[22m
    Property is configurable [1m[32mOK[39m[22m

[1m  Uses the this value if it's a function[22m
    Observable.of will use the 'this' value if it is callable [1m[32mOK[39m[22m

[1m  Uses 'Observable' if the 'this' value is not a function[22m
    Observable.of will use 'Observable' if the this value is not callable [1m[32mOK[39m[22m

[1m  Arguments are delivered to next[22m
    All items are delivered and complete is called [1m[32mOK[39m[22m

[1mObservable.from[22m

[1m  Observable has a from property[22m
    Property from exists on the object [1m[32mOK[39m[22m
    Property has a function value [1m[32mOK[39m[22m
    Function length is 1 [1m[32mOK[39m[22m
    Property is writable [1m[32mOK[39m[22m
    Property is non-enumerable [1m[32mOK[39m[22m
    Property is configurable [1m[32mOK[39m[22m

[1m  Allowed argument types[22m
    Null is not allowed [1m[32mOK[39m[22m
    Undefined is not allowed [1m[32mOK[39m[22m
    Undefined is not allowed [1m[32mOK[39m[22m

[1m  Uses the this value if it's a function[22m
    Observable.from will use the 'this' value if it is callable [1m[32mOK[39m[22m

[1m  Uses 'Observable' if the 'this' value is not a function[22m
    Observable.from will use 'Observable' if the this value is not callable [1m[32mOK[39m[22m

[1m  Symbol.observable method is accessed[22m
    Symbol.observable property is accessed once [1m[32mOK[39m[22m
    Symbol.observable must be a function [1m[32mOK[39m[22m
    Symbol.observable must be a function [1m[32mOK[39m[22m
    Symbol.observable must be a function [1m[32mOK[39m[22m
    Symbol.observable must be a function [1m[32mOK[39m[22m
    Calls the Symbol.observable method [1m[32mOK[39m[22m

[1m  Return value of Symbol.observable[22m
    Throws if the return value of Symbol.observable is not an object [1m[32mOK[39m[22m
    Throws if the return value of Symbol.observable is not an object [1m[32mOK[39m[22m
    Throws if the return value of Symbo [...]

2016-12-06 19:44 UTC, rorticus commented
A couple of notes,

The ES spec tests have some pretty specific requirements about properties being non-enumerable, and certain object prototypes being `Object`, which is the cause for the weird factory methods I have.  In addition, the properties must exist on the *prototype* of the object, not the object itself.  As such, I need to create a new prototype each time I create a subscription.

I was wondering if you guys knew of an approach where I could use a static prototype, but still have certain internal variables (`closed`, `cleanup`, `start`, etc) not publicly accessible (i.e., in `startSubscription` I am capturing the `executor` and `observer` and using them later, but they shouldn't be accessible inside a subscribing object).

2016-12-07 12:43 UTC, agubler requested changes
Lost of `else`, `else if` and `catch`'s that need to be on a new line.

2016-12-07 12:43 UTC, agubler commented on src/Observable.ts
> +		let cleanUp: any;
I think we can type `cleanUp` to the union type return of the executor.

2016-12-07 12:43 UTC, agubler commented on src/Observable.ts
> +				else if (result !== undefined && result !== null) {
can it just be `(result)`?

2016-12-07 12:43 UTC, agubler commented on src/Observable.ts
> +				} else if (cleanUpError) {
new line for `else if`

2016-12-07 12:43 UTC, agubler commented on src/Observable.ts
> +				} else if (cleanUpError) {
And `else` above ^^^

2016-12-07 13:08 UTC, rorticus commented on src/Observable.ts
> +		let cleanUp: any;
So `cleanUp` is either `undefined` or a method with no parameters and no return value, so I've typed it as such (not just the return value of `executor`).

2016-12-07 13:09 UTC, rorticus commented on src/Observable.ts
> +				else if (result !== undefined && result !== null) {
Unfortunately not.. if the return value is `undefined` or `null`, no error. But if the return value is the number `0` or `false`, we want to error.

2016-12-07 13:09 UTC, rorticus commented on src/Observable.ts
> +				} else if (cleanUpError) {
Fixed all those :)

2016-12-07 13:10 UTC, agubler commented on src/Observable.ts
> +				else if (result !== undefined && result !== null) {
Roger that.

2016-12-07 13:14 UTC, agubler approved these changes
nice one @rorticus

2016-12-07 13:25 UTC, merged